/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    KActionSheet: typeof import('./src/components/kActionSheet/kActionSheet.vue')['default']
    KBaseLayout: typeof import('./src/components/kBaseLayout/kBaseLayout.vue')['default']
    KCard: typeof import('./src/components/kCard/kCard.vue')['default']
    KDownChoice: typeof import('./src/components/kDownChoice/kDownChoice.vue')['default']
    KEmpty: typeof import('./src/components/kEmpty/kEmpty.vue')['default']
    KFluctuationText: typeof import('./src/components/KFluctuationText/KFluctuationText.vue')['default']
    KHashCalendar: typeof import('./src/components/kHashCalendar/kHashCalendar.vue')['default']
    KHeaderSearch: typeof import('./src/components/kHeaderSearch/kHeaderSearch.vue')['default']
    KLoading: typeof import('./src/components/kLoading/kLoading.vue')['default']
    KMaskCover: typeof import('./src/components/kMaskCover/kMaskCover.vue')['default']
    KNoticebar: typeof import('./src/components/kNoticebar/kNoticebar.vue')['default']
    KTabbar: typeof import('./src/components/kTabbar/kTabbar.vue')['default']
    KTable: typeof import('./src/components/kTable/kTable.vue')['default']
    KTopTabbar: typeof import('./src/components/kTopTabbar/kTopTabbar.vue')['default']
    NutActionSheet: typeof import('nutui-uniapp/components/actionsheet/actionsheet.vue')['default']
    NutAvatar: typeof import('nutui-uniapp/components/avatar/avatar.vue')['default']
    NutButton: typeof import('nutui-uniapp/components/button/button.vue')['default']
    NutCell: typeof import('nutui-uniapp/components/cell/cell.vue')['default']
    NutCellGroup: typeof import('nutui-uniapp/components/cellgroup/cellgroup.vue')['default']
    NutDatePicker: typeof import('nutui-uniapp/components/datepicker/datepicker.vue')['default']
    NutDialog: typeof import('nutui-uniapp/components/dialog/dialog.vue')['default']
    NutDrag: typeof import('nutui-uniapp/components/drag/drag.vue')['default']
    NutEmpty: typeof import('nutui-uniapp/components/empty/empty.vue')['default']
    NutForm: typeof import('nutui-uniapp/components/form/form.vue')['default']
    NutFormItem: typeof import('nutui-uniapp/components/formitem/formitem.vue')['default']
    NutGrid: typeof import('nutui-uniapp/components/grid/grid.vue')['default']
    NutGridItem: typeof import('nutui-uniapp/components/griditem/griditem.vue')['default']
    NutIcon: typeof import('nutui-uniapp/components/icon/icon.vue')['default']
    NutInfiniteLoading: typeof import('nutui-uniapp/components/infiniteloading/infiniteloading.vue')['default']
    NutInput: typeof import('nutui-uniapp/components/input/input.vue')['default']
    NutList: typeof import('nutui-uniapp/components/list/list.vue')['default']
    NutMarquee: typeof import('nutui-uniapp/components/marquee/marquee.vue')['default']
    NutMenu: typeof import('nutui-uniapp/components/menu/menu.vue')['default']
    NutMenuItem: typeof import('nutui-uniapp/components/menuitem/menuitem.vue')['default']
    NutNavbar: typeof import('nutui-uniapp/components/navbar/navbar.vue')['default']
    NutNoticebar: typeof import('nutui-uniapp/components/noticebar/noticebar.vue')['default']
    NutPicker: typeof import('nutui-uniapp/components/picker/picker.vue')['default']
    NutPopup: typeof import('nutui-uniapp/components/popup/popup.vue')['default']
    NutProgress: typeof import('nutui-uniapp/components/progress/progress.vue')['default']
    NutSearchbar: typeof import('nutui-uniapp/components/searchbar/searchbar.vue')['default']
    NutSwiper: typeof import('nutui-uniapp/components/swiper/swiper.vue')['default']
    NutSwiperItem: typeof import('nutui-uniapp/components/swiperitem/swiperitem.vue')['default']
    NutTable: typeof import('nutui-uniapp/components/table/table.vue')['default']
    NutTabPane: typeof import('nutui-uniapp/components/tabpane/tabpane.vue')['default']
    NutTabs: typeof import('nutui-uniapp/components/tabs/tabs.vue')['default']
    NutToast: typeof import('nutui-uniapp/components/toast/toast.vue')['default']
    NutUploader: typeof import('nutui-uniapp/components/uploader/uploader.vue')['default']
  }
}
